### ISSUE TITLE
Create orm.xml at build time

### ISSUE THREAD

**Issue by dtaimanov** [Haulmont/jmix-data#15]
Second part of Haulmont/jmix-data#5
Move `io.jmix.data.impl.MappingFileCreator` logic into `io.jmix.gradle.EnhancingAction`

##### Tasks:
- [x] Generate the same `orm.xml` at build time
- [x] Disable runtime `orm.xml` generation and fix possible problems, look for exceptions in logs
- [ ] Refactor (remove) `io.jmix.data.impl.PersistenceConfigProcessor.java`
- [ ] Recheck and improve existitng tests: cover all common cases, cover specific cases when it is reasonable

#### Important changes:
Property `jmix.disableOrmXmlGeneration` has been removed.
